stages:
  - deploy
  - test

deploy_dev:
  stage: deploy
  only:
    - master
    - main
    - dev
  tags:
    - hva
  environment: Development
  script:
    - apk update
    - apk add openssh
    - apk add lftp
    - apk add wget
    - lftp -e "set net:max-retries 3; set ssl:verify-certificate no; set ftp:ssl-allow yes; set sftp:auto-confirm yes; open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST; mirror -Rv server/ $FTP_TARGETPATH/app/ --ignore-time --parallel=10"
    - lftp -e "set net:max-retries 3; set ssl:verify-certificate no; set ftp:ssl-allow yes; set sftp:auto-confirm yes; open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST; mirror -Rv src/ $FTP_TARGETPATH/wwwroot/ --ignore-time --parallel=10"
    - 'wget --header="Authorization: $API_KEY" https://hbo-ict.cloud/api/Docker/$API_SUBDOMAIN/Restart'

deploy_live:
  stage: deploy
  only:
    - live
  tags:
    - hva
  environment: Live
  script:
    - apk update
    - apk add openssh
    - apk add lftp
    - apk add wget
    - lftp -e "set net:max-retries 3; set ssl:verify-certificate no; set ftp:ssl-allow yes; set sftp:auto-confirm yes; open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST; mirror -Rv server/ $FTP_TARGETPATH/app/ --ignore-time --parallel=10"
    - lftp -e "set net:max-retries 3; set ssl:verify-certificate no; set ftp:ssl-allow yes; set sftp:auto-confirm yes; open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST; mirror -Rv src/ $FTP_TARGETPATH/wwwroot/ --ignore-time --parallel=10"
    - 'wget --header="Authorization: $API_KEY" https://hbo-ict.cloud/api/Docker/$API_SUBDOMAIN/Restart'

cypress:
  stage: test
  image: cypress/browsers:latest
  parallel: 2
  tags:
    - hva
  script:
    - cd server
    - npm ci
    - npm run e2e
  artifacts:
    when: on_success
    paths:
      - server/cypress/results/test-output.xml
      - server/cypress/screenshots
    reports:
      junit: server/cypress/results/test-output.xml

cypress_artifacting:
  stage: test
  tags:
    - hva
  script:
    - echo "✅ Unit Tests Complete ✅ - Attached Reporter JUnit - $CI_PROJECT_DIR"
  needs:
    - job: cypress
      artifacts: true
  dependencies:
    - cypress
